### ISSUE TITLE
T2 - Stretch Goals - EventShare

### ISSUE THREAD

**Issue by kyvycodes** [EventShare-WDF-2004/EventShare#77]
**User:**
- [x] User can add profile pic #68
- [x] Have a seamless UX/UI for users to navigate easily (second draft - builds off first)
- [x] As a guest, I want to be able to suggest a task
- [x] Integration with google calendar
- [x] Address gives user directions 
- [ ] Add itinerary for the event
- [x] User should be able to signup/login with Google #44 
- [ ] User should be able to signup/login with Facebook

**As host I should be able to edit and delete:**
- [x] tasks 
- [x] events 
- [x] polls

**Routes (Security):**
- [ ] As a user the API route for my profile should only be available to the user requesting it #35 

**Notifications/Reminders:** 
- [x] A user should receive notifications when new poll has been created to vote on the poll 

**Follow up reminders, either in-app or through some third-party service**
- [ ] Send a reminder via email or text to all users (RSVP list) who are attending the event that the event is close #7 
- [ ] when event date is close by

**Social Aspect:**
- [ ] Chat functionality to discuss plans
- [x] Social aspect where users can have add friends and view their friends’ past event for ideas
- [x] Users can share photos that accorded during the event 
- [ ] For bigger events we will have third parties API’s that allows you to search for services/providers to your party (i.e. food, drinks, flowers, decorations, music,)

- [ ] Make progressive app #46
